name: JUnit Test Workflow

on:
  workflow_dispatch:

jobs:
  run-junit-tests:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Run JUnit tests with Maven
        run: mvn test
